server:
  port: 9009
spring:
  application:
    name: tensquare‐sms
  rabbitmq:
    host: 192.168.248.136
    username: guest
    password: guest
    port: 5672

aliyun:
  sms:
    template: SMS_93975002
    sign: 讲解项目物流bos
    accessKeyId: LTAI4GBvog8zjWtBAJkBxvYz
    accessKeySecret: o4sIDNNCb9ADaLO0iNENM5LjMSNvVW
#    template_code: SMS_85735065
#    sign_name: 黑马

